version: '2.2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: es790
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: basic
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kib:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: kibana790
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es790:9200
      ELASTICSEARCH_HOSTS: http://es790:9200
    networks:
      - elastic


volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge