apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-qa
spec:
  replicas: 3
  selector:
    appxxx: nginx
  template:
    metadata:
      name: nginx
      labels:
        appxxx: nginx
        environment: qa
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
